### ISSUE TITLE
Input field for documenting result for a test re-renders on change event

### ISSUE THREAD

**Issue by ojwanganto** [openmrs/openmrs-esm-laboratory#35]
When entering results for a test, the input field loses focus on change event. This may not be almost apparent for select fields but is a trouble for text fields. 

Have a look at https://github.com/openmrs/openmrs-esm-laboratory/blob/main/src/results/result-form.component.tsx#L188 which renders questions - a list of input fields for document results

**Comment by harshdew02** [comment]
Hello, @ojwanganto I am interested in working on this issue and trying to set up a development environment in my system but it asks for a User name and password. when I put Username: admin and Password: Admin123 it says invalid, please provide me some guidance.

**Comment by ojwanganto** [comment]
Hello @harshdew02. Thanks for your interest in this. We changed the implementation approach to use react forms hook and that solved the error. We should ideally close the issue. Thanks so much
